[package]
name = "esp32c3-working"
version = "0.1.0"
edition = "2021"

[dependencies]
embassy-executor = { version = "0.5.0" }
embassy-sync = "0.6.0"
embassy-time = { version = "0.3.1", default-features = false }
esp-backtrace = { version = "0.12.0", features = ["esp32c3", "exception-handler", "panic-handler", "println"] }
esp-hal = { version = "0.18.0", features = ["esp32c3"] }
esp-hal-embassy = { version = "0.1.0", features = ["esp32c3", "integrated-timers", "time-timg0"] }
esp-println = { version = "0.9.1", features = ["esp32c3"] }
heapless = "0.8.0"

[profile.release]
lto = true
strip = true
codegen-units = 1
incremental = false
opt-level = "z"
