[build]
target = "riscv32imc-unknown-none-elf"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  # add defmt support
  "-C", "link-arg=-Tdefmt.x",
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

[unstable]
build-std = ["core"]

[target.'cfg(any(target_arch = "riscv32", target_arch = "xtensa"))']
# runner = "probe-rs attach --chip esp32c3"
runner = "espflash flash --monitor -L defmt"
